### ISSUE TITLE
Does it work properly in the z2_row?

### ISSUE THREAD

**Issue by hyman-lee** [davidevinavil/android_device_zuk_z2_row#2]

**Comment by davidevinavil** [comment]
yes

**Comment by hyman-lee** [comment]
I meet with a error, could you give me some help?
My System: Ubuntu 16.04
JDK-version: openjdk-8

Starting build with ninja
ninja: Entering directory `.'
ninja: error: '/.txt', needed by '/home/hyman/lineage14.1/out/target/common/obj/PACKAGING/checkpublicapi-cm-last-timestamp', missing and no known rule to make it
build/core/ninja.mk:151: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1
make: Leaving directory '/home/hyman/lineage14.1
I meet with it for 4 days, I almost go mad.
Please help me, thank you!

**Comment by FFY00** [comment]
Do you mind to share how you fixed the error? Thanks
